project:
  type: website

website:
  title: "MS-AutoQC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - overview.qmd
      - download.qmd
      - installation.qmd
      - get-started.qmd
      - user-guide.qmd
      - documentation.qmd
      - troubleshooting.qmd
      - faq.qmd

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    fontsize: 1.05em
    css: styles.css
    toc: true